log:
  output: STDOUT
  level:  DEBUG
alarm:
  location: http://localhost:3000/alarms.json
  check_period: 60
holiday:
  location: http://s-proj.com/utils/checkHoliday.php
  case_of_true: ['hoiday']
  case_of_false: ['else']
itunes:
  rss:
    topsongs: 'https://itunes.apple.com/jp/rss/topsongs/limit=4/xml'
    topalbums: https://itunes.apple.com/jp/rss/topalbums/limit=4/xml
