web:
  build: web
  container_name: rpiclock_web
  command: bundle exec rails s -p 3000 -b '0.0.0.0'
  volumes:
    - ./web:/app
  ports:
    - "3000:3000"

alarm:
  build: alarm
  container_name: rpiclock_alarm
  command: /usr/bin/supervisord -c supervisord.conf
  volumes:
    - ./alarm:/app
    - /var/run/dbus:/var/run/dbus
    - /dev/snd:/dev/snd:rw
  links:
    - web:localhost
  privileged: true
