# Docker base image
FROM resin/rpi-raspbian:jessie

# install required packages
RUN apt-get update -qq
RUN apt-get install -y ruby ruby-dev bundler
RUN apt-get install -y mplayer2 libav-tools supervisor
RUN apt-get clean

# build app environment
RUN mkdir /app
WORKDIR /app
ADD Gemfile /app/Gemfile
RUN touch /app/Gemfile.lock
RUN bundle install
